### ISSUE TITLE
pygrib 1.9.9

### ISSUE THREAD

**Issue by wpreimes** [TUW-GEO/ecmwf_models#11]
Hey! I was just fixing some CI issues. All python versions are passing now, but I saw that there are CI environments for pygrib version 1.9.9 and version 2.0.1. Or at least there should be, because until now only version 2.0.1 was tested (which was installed last from the requirements.txt via `pip install -r requirements.txt` in .travis.yml).

Now I have the 2 versions working, and tests fail for version 1.9.9 as some of the metadata stuff is handled differently it seems. 
e.g `grbs.message(1)['levels']`  returns` u'0-7'` for v2.0.1 but `u'7'` for v1.9.9 (on the same file)

Should we support and test v1.9.9? Otherwise I would just set pygrib>=2.0.1 as the required version if thats ok for you?

**Comment by sebhahn** [comment]
Fine for me

**Comment by cpaulik** [comment]
I think pygrib 1.9.9 was tested. 

See e.g. https://travis-ci.org/TUW-GEO/ecmwf_models/jobs/456861222#L895 which does not update pygrib.

Anyway, I don't remember why we supported both and dropping support now should be fine.
